### ISSUE TITLE
Query must be set

### ISSUE THREAD

**Issue by RiveraJones** [utiso/dorkbot#14]
Hello, I'm trying to run Dorkbok with the following command:

python ./dorkbot.py -i google -o engine=GoogleCSE,query="filetype:php inurl:id" -s arachni

And I get this error:

-ERROR - query must be set

Why is this error?

**Comment by jgor** [comment]
Whoops, the Quickstart section was using outdated syntax (fixed, thanks!). You'll specify each option as a separate -o, e.g.:
`python ./dorkbot.py -i google -o engine=GoogleCSE -o query="filetype:php inurl:id" -s arachni`
