### ISSUE TITLE
Searching for Multiple Index Queries

### ISSUE THREAD

**Issue by LiamWBA** [utiso/dorkbot#20]
I was  wondering if there is a way of searching for multiple index queries at a time. 

Say i have a list of 100 popular google dorking search terms and I would like to feed all these into dorkbot at once. Is there an option to feed in a text file line by line in the `-o query=` option. If not what would be the best way to acheive this? Ideally, I want to avoid manually performing 100 scans.

**Comment by jgor** [comment]
It sounds like you'd want a single query with each term separated by " OR ".
