### ISSUE TITLE
Issues running dorkbot

### ISSUE THREAD

**Issue by ctgreen78** [utiso/dorkbot#3]
All requirements are met but when I run **./dorkbot.py -s arachni** nothing happens. Thanks.
![dorkbot](https://user-images.githubusercontent.com/34352828/38317646-8a15a764-37fb-11e8-8f21-b4a24b454135.JPG)

**Comment by jgor** [comment]
Have you run an indexer module to add targets already? Can you confirm that **./dorkbot.py -l** lists at least one target?

**Comment by ctgreen78** [comment]
Thanks for the quick response. Are you referring to this?
![dorkbot 2jpg](https://user-images.githubusercontent.com/34352828/38321416-a147cb92-3805-11e8-9290-78a2ffa60f46.JPG)

**Comment by jgor** [comment]
Yes, did that command produce any results? It would have printed any urls that it gathered, and you can double-check by running **./dorkbot.py -l** to see if anything is in the database. If the database is empty then the scan module will not do anything.

**Comment by ctgreen78** [comment]
When I run the above command, nothing happens. Perhaps there is an issue with my CSE id.

**Comment by ctgreen78** [comment]
I understand how it works now. Now when I run ./dorkbot.py -s arachni  it shows "Running". Thank you so much for the help.

**Comment by jgor** [comment]
Excellent, glad it worked out!
