### ISSUE TITLE
Arachni scan report format

### ISSUE THREAD

**Issue by ctgreen78** [utiso/dorkbot#4]
Hey Jgor, is this the correct format of Arachni generated report? Thanks.

![dorkbot3](https://user-images.githubusercontent.com/34352828/38344557-2df1954e-3858-11e8-9a0b-3278d29888a5.JPG)

**Comment by jgor** [comment]
No, that's a temporary file for stderr error output. If that file exists after the scan is complete, it means there was an error, and you can read the contents of the file for a clue as to why. When a scan completes successfully that file will disappear and a .json report will be there instead.
