### ISSUE TITLE
slow if scanning in bulk

### ISSUE THREAD

**Issue by Thiploll** [utiso/dorkbot#5]
Hello sometimes it takes 2-5 sec each dork to scan, this is fairly slow if i want to scan 100 dorks , any way to fix this ?

**Comment by jgor** [comment]
I would expect most scans to take minutes at least, not seconds. Which scanner module are you using, arachni or wapiti?

Or are you talking about an indexer module instead of a scanner module? Feel free to include the command you're using and I can perhaps comment further.

**Comment by Thiploll** [comment]
ok i got multithreading on my side working altrough if i do to many threads i start getting errors

**Comment by Thiploll** [comment]
Prob because the main program isnt meant to write many things at the database at once , idk its going to fast to spot the error

**Comment by Thiploll** [comment]
Traceback (most recent call last):
  File "dorkbot.py", line 272, in <module>
    main()
  File "dorkbot.py", line 32, in main
    index(db, args.indexer, parse_options(args.indexer_options))
  File "dorkbot.py", line 124, in index
    results = module.run(options)
  File "/root/dorkbot/indexers/google.py", line 40, in run
    results = get_results(index_cmd)
  File "/root/dorkbot/indexers/google.py", line 49, in get_results
    output = subprocess.check_output(index_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/root/dorkbot/indexers/../tools/phantomjs/bin/phantomjs', '--ignore-ssl-errors=true', '/root/dorkbot/indexers/google.js', 'myhotkey69', 'hotdork69']' returned non-zero exit status 1


is one of the errors i often get

**Comment by Thiploll** [comment]
could this be  because the key has a daily limit ? i use many keys  and some work some stop working after some time

**Comment by jgor** [comment]
Yeah, I think this is some sort of (unpublished?) limit on Google's side. I get similar errors when running too many instances, and it's because the website has stopped returning results for that engine.

**Comment by Thiploll** [comment]
You think multiple keys / gcse will help fix the problem ?
